---
- name: Pull Docker Image from Docker Hub
  hosts: localhost
  remote_user: sejal
  become: true
  tasks:
    - name: Pull Docker Image
      docker_image:
        name: "sejal28/calculator"
        source: pull
      register: docker_pull_result

    - name: Display Docker Pull Result
      debug:
        var: docker_pull_result

    - name: Ensure Docker service is started
      service:
        name: docker
        state: started

    - name: Run Docker Container
      docker_container:
        name: calculator
        image: "sejal28/calculator"
        state: started
